apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configmapsecretsyncs.apps.muntashirislam.com
spec:
  group: apps.muntashirislam.com
  names:
    kind: ConfigMapSecretSync
    listKind: ConfigMapSecretSyncList
    plural: configmapsecretsyncs
    singular: configmapsecretsync
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              sourceNamespace:
                type: string
              targetNamespaces:
                type: array
                items:
                  type: string
              configMapNames:
                type: array
                items:
                  type: string
              secretNames:
                type: array
                items:
                  type: string