# permissions for end users to edit configmapsecretsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: configmapsecretsync-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: config-secrets-sync-operator
    app.kubernetes.io/part-of: config-secrets-sync-operator
    app.kubernetes.io/managed-by: kustomize
  name: configmapsecretsync-editor-role
rules:
- apiGroups:
  - apps.muntashirislam.com
  resources:
  - configmapsecretsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.muntashirislam.com
  resources:
  - configmapsecretsyncs/status
  verbs:
  - get
